language: android
sudo: required
jdk: oraclejdk8
android: 
   components:
      - tools
      - platform-tools
      - tools
      - build-tools-29.0.1
      - android-29
      - extra-android-m2repository
#optional, use it if only you haven't give permission yet.
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-29"
#   - mkdir "$ANDROID_HOME/licenses" || true
#   - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
#   - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
#   - yes | sdkmanager --update
#   - yes | sdkmanager --licenses
script:
   - ./gradlew build
after_success:
  - bash <(curl -s https://codecov.io/bash)